- name: Velocity
  url: "#hook"
  summary: A responsive website template designed to help startups promote, market and sell their products.

- name: DevStudio
  url: "http://themes.3rdwavemedia.com/website-templates/responsive-bootstrap-theme-web-development-agencies-devstudio/"
  summary: A responsive website template designed to help web developers/designers market their services.

- name: Tempo
  url: "http://themes.3rdwavemedia.com/website-templates/responsive-bootstrap-theme-for-startups-tempo/"
  summary: A responsive website template designed to help startups promote their products or services and to attract users &amp; investors

- name: Atom
  url: h"http://themes.3rdwavemedia.com/website-templates/responsive-bootstrap-theme-mobile-apps-atom/"
  summary: A comprehensive website template solution for startups/developers to market their mobile apps.

- name: Delta
  url: "http://themes.3rdwavemedia.com/website-templates/responsive-bootstrap-theme-for-mobile-apps-delta/"
  summary: A responsive Bootstrap one page theme designed to help app developers promote their mobile apps
